
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcxanvxxgovomixgdved.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjeGFudnh4Z292b21peGdkdmVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NTEwMDQsImV4cCI6MjA2NDIyNzAwNH0.CbEmqD8IkSxrfEaO85IDKcCBzwPduhuBOyT2mXFWTXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
